version: '3'
services:
  corb:
    image: "ezbc/corb:${CORB_VERSION}"
    hostname: corb
    volumes:
      - ./:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR} 
  odh:
    hostname: odh
    image: "ezbc/odh:${ODH_VERSION}"
    command: "java -jar /opt/odh/quick-start.war"
    ports:
      - "${ODH_PORT}:8080"
    volumes:
      - ./odh/:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR}
  marklogic:
    image: "ezbc/marklogic:${ML_VERSION}"
    hostname: marklogic
    volumes:
      - "${LOCAL_VOLUME_DIR}/marklogic${ML_VERSION}:/var/opt/MarkLogic"
    ports:
      - "${ML_PORT_LOWER}-${ML_PORT_UPPER}:${ML_PORT_LOWER}-${ML_PORT_UPPER}"
    command: /bin/sh -c "/etc/init.d/MarkLogic start && tail -f /dev/null"
  mlcp:
    image: "ezbc/mlcp:${MLCP_VERSION}"
    hostname: mlcp
    volumes:
      - ./:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR} 
  slush:
    hostname: slush
    image: "ezbc/slush-discovery:${SLUSH_VERSION}"
    ports:
      - "${SLUSH_APP_PORT}:${SLUSH_APP_PORT}"
      - "${SLUSH_ML_APP_PORT}:${SLUSH_ML_APP_PORT}"
      - "${SLUSH_NODE_PORT}:${SLUSH_NODE_PORT}"
    volumes:
      - ./slush/:${CONTAINER_WORKING_DIR}
    working_dir: ${CONTAINER_WORKING_DIR}
    command: /bin/sh -c "npm install && bower install --allow-root && gulp serve-local && tail -f /dev/null"
